version: '3.3'
services:
    api:
      image: node:18-alpine
      container_name: api
      working_dir: /home/node/app
      restart: always    
      entrypoint: docker/scripts/entrypoint.sh
      volumes:
        - ./:/home/node/app
      ports:
        - 3333:3333
      env_file:
        - .env
      