name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/minozzzi/aws-nest-api:latest .

      - name: Tag and push Docker image to GHCR
        run: |
          docker tag aws-nest-api:latest ghcr.io/minozzzi/aws-nest-api:latest
          docker push ghcr.io/minozzzi/aws-nest-api:latest

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/minozzzi/aws-nest
            docker stop aws-nest-api || true
            docker rm aws-nest-api || true
            docker run -d --name aws-nest-api -p 3333:3333 ghcr.io/minozzzi/aws-nest
